#!/bin/bash -e

# /usr/local/sbin/raspi-monitor
# Hdmi sinyalini acar kapatir.
# Inspiration: http://www.raspberrypi.org/forums/viewtopic.php?t=16472&p=176258

CMD="$1"

function on {
    /opt/vc/bin/tvservice --preferred

    # terminal init:
    chvt 6
    chvt 7
}

function off {
    /opt/vc/bin/tvservice --off
}

function must_be_root {
    if [ $USER != root ]; then
        echo "ERROR: Root olarak calistir"
        exit 1
    fi
}

function main {
    must_be_root
    if [ "$CMD" == "on" ]; then
        on
    elif [ "$CMD" == "off" ]; then
        off
    else
        echo "Kullanim: $0 <on|off>"
        exit 1
    fi
    exit 0
}

main

